builbo: add error handling for the buiuld action
Signed-off-by: Michael Adam <obnox@samba.org>

diff --git a/builbo b/builbo
--- a/builbo
+++ b/builbo
@@ -139,6 +139,18 @@ usage
 exit 1
 fi
 
+if [ "$ACTION" = "build" ]; then
+
+    if [ -z "$BUILD_CMD" ]; then
+
+        echo "error: action 'build' requires --build-script (-s)"
+        usage
+        exit 1
+    fi
+
+
+fi
+
 
 
 
